### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by ditopcu** [lumpysimon/blipfoto-wordpress-importer#4]
Installation steps are not clear:

10.Copy the 'Client ID', 'Client secret' and 'Access token' into the relevant fields on the settings page on your WordPress website.
11. Set the other options as required.

Could you expand this? 

Thanks

**Comment by lumpysimon** [comment]
They are referring to the settings page from step 1 (go to your admin dashboard, then go to _Blipfoto Importer_ under the _Settings_ menu). Each option has a description explaining what it is.

**Comment by ditopcu** [comment]
Thanks for quick reply..

I have managed to run plugin.. Thank you..

**Comment by lumpysimon** [comment]
Great!
