### ISSUE TITLE
Plugin doesn't Activate

### ISSUE THREAD

**Issue by Orangeaurochs** [lumpysimon/blipfoto-wordpress-importer#8]
I have a fresh installation of Wordpress (version 4.1.1) at http://moosviews.aurochs.org/
The Blipfoto Importer plugin Imports OK but fails to Activate and gives the following error:

Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /[...path...]wp-content/plugins/blipfoto-importer/blipfoto-importer.php on line 73

As far as my limited understanding of php goes I can't see any mismatched parentheses and that line ("use Blipfoto\Api\Client;") doesn't have any although that line looks odd to me. I don't know how this plays with WP too though.

Any help you can give would be great as this plugin looks just the ticket and I see other people have managed to use it OK.

Thanks,

Tom

**Comment by Orangeaurochs** [comment]
I think from looking at forums for plugins with similar problems that this may have something to do with the version of PHP my server is using: currently 5.2 but should probably be 5.3 or 5.4. I have contacted them.

**Comment by lumpysimon** [comment]
Hi Tom

Yes, that's a PHP version compatibility problem I'm afraid. Ask your host if they can upgrade you to PHP5.6 or 5.5 if possible, but 5.4 is also good.

Cheers
Simon

**Comment by Orangeaurochs** [comment]
Hello. Thank you for getting back to me! I asked the hosting company and they could only upgrade quickly by moving to a different machine which would break several websites for a while. Never mind, because this looked perfect. I've managed at least to take a copy of the content to my laptop using some python software my wife found. Hopefully blip will live happily ever after anyway...
