### ISSUE TITLE
Does not appear to be working ...

### ISSUE THREAD

**Issue by garethbult** [lumpysimon/blipfoto-wordpress-importer#9]
I'm trying this on WP 4.2, and after putting all the credentials in and going to run the importer, it just gives me a page saying "Blipfoto Importer" and sites there.. (forever) .. nothing gets imported.

**Comment by lumpysimon** [comment]
I've tested it on a couple of WordPress 4.2 sites and it's worked ok.

Could you try lowering the 'Number of entries' setting (try 5, or even lower) and see if that works. If so, then it sounds like your server is low on memory.

If that makes no difference, do you know which version of PHP you're using?

**Comment by lumpysimon** [comment]
Closing (no further response)
